---
atlas: &atlas
  x: 0.225
  y: 0.88
  font: 73
  size: 25
  label: ATLAS

internal: &internal
  x: 0.35
  font: 43
  label: Internal
  <<: *atlas

atlasinternal: &atlasinternal
  - *atlas
  - *internal

groups:
  - name: "t#bar{t}"
    files:
      - 2016_tag01_v1_dPhiMETMin_0p0/ttbarInc_0L/fetch/data-optimizationTree/*410000*.merged
      - 2016_tag01_v1_dPhiMETMin_0p0/ttbarExc_0L/fetch/data-optimizationTree/*407012*.merged
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  - name: dijets
    files:
      - 2016_tag01_v1_dPhiMETMin_0p0/dijet_0L/fetch/data-optimizationTree/*.merged
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  - name: W+jets
    files:
      - 2016_tag01_v1_dPhiMETMin_0p0/Wsherpa_0L/fetch/data-optimizationTree/*.merged
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  - name: Z+jets
    files:
      - 2016_tag01_v1_dPhiMETMin_0p0/Zsherpa_0L/fetch/data-optimizationTree/*.merged
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  - name: "1-top: t-channel"
    files:
      - 2016_tag01_v1_dPhiMETMin_0p0/singletop_0L/fetch/data-optimizationTree/*410011*.merged
      - 2016_tag01_v1_dPhiMETMin_0p0/singletop_0L/fetch/data-optimizationTree/*410012*.merged
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  - name: "1-top: Wt-inclusive"
    files:
      - 2016_tag01_v1_dPhiMETMin_0p0/singletop_0L/fetch/data-optimizationTree/*410013*.merged
      - 2016_tag01_v1_dPhiMETMin_0p0/singletop_0L/fetch/data-optimizationTree/*410014*.merged
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  - name: top EW
    files:
      - 2016_tag01_v1_dPhiMETMin_0p0/topEW_0L/fetch/data-optimizationTree/*.merged
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  - name: diboson
    files:
      - 2016_tag01_v1_dPhiMETMin_0p0/diboson_0L/fetch/data-optimizationTree/*.merged
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  - name: "m_{#tilde{g}} = 1700, m_{#tilde{#chi}} = 200"
    files:
      - 2016_tag01_v1_dPhiMETMin_0p0/Gtt_0L/fetch/data-optimizationTree/*370153*.merged
    styles:
      legendstyle: L
      drawstyle: hist
      linewidth: 2
    stack it: false
    scale factor: 2000.0

  - name: "m_{#tilde{g}} = 1700, m_{#tilde{#chi}} = 600"
    files:
      - 2016_tag01_v1_dPhiMETMin_0p0/Gtt_0L/fetch/data-optimizationTree/*370155*.merged
    styles:
      legendstyle: L
      drawstyle: hist
      linewidth: 2
    stack it: false
    scale factor: 2000.0

  - name: "m_{#tilde{g}} = 1700, m_{#tilde{#chi}} = 1000"
    files:
      - 2016_tag01_v1_dPhiMETMin_0p0/Gtt_0L/fetch/data-optimizationTree/*370157*.merged
    styles:
      legendstyle: L
      drawstyle: hist
      linewidth: 2
    stack it: false
    scale factor: 2000.0

  - name: "m_{#tilde{g}} = 1700, m_{#tilde{#chi}} = 1345"
    files:
      - 2016_tag01_v1_dPhiMETMin_0p0/Gtt_0L/fetch/data-optimizationTree/*370159*.merged
    styles:
      legendstyle: L
      drawstyle: hist
      linewidth: 2
    stack it: false
    scale factor: 2000.0

# plots:
#   config:  # here we set global configurations that are applied uniformly such as...
#     canvas:
#     legend:
#     texts:

plots:
  config:
    texts:
      - *atlas
      - *internal
      - &topline
        x: 0.25
        y: 0.84
        font: 43
        size: 18
        label: "#sqrt{s} = 13 TeV, L_{int} #approx 3.2 fb^{-1}"
      - <<: *topline
        y: 0.80
        label: "Preselection, signal #times 2000"
      - <<: *topline
        y: 0.76
        label: "min(#Delta#phi^{MET}) > 0.0"

    canvas:
      width: 650
      height: 500
      logy: false
      ndivisions: 505
    legend:
      leftmargin: 0.425
      topmargin: 0.025
      rightmargin: 0.075
      textsize: 14
      entrysep: 0.01
      entryheight: 0.02

  paths:
    #all/SR_Gtt_0l_A/met: {}
    #all/SR_Gtt_0l_A/meff: {}
    #all/SR_Gtt_0l_A/dphimetmin: {}
    #all/SR_Gtt_0l_A/mtb: {}
    #all/SR_Gtt_0l_A/njets: {}
    #all/SR_Gtt_0l_A/nbjets: {}
    #all/SR_Gtt_0l_A/ntops: {}
    #all/SR_Gtt_0l_A/razor_GG_mass: {}
    #all/SR_Gtt_0l_A/razor_Ga_mass: {}
    #all/SR_Gtt_0l_A/razor_Gb_mass: {}
    #all/SR_Gtt_0l_A/razor_Ca1_mass: {}
    #all/SR_Gtt_0l_A/razor_Cb1_mass: {}
    #all/SR_Gtt_0l_A/razor_Va1_mass: {}
    #all/SR_Gtt_0l_A/razor_Vb1_mass: {}
    #all/SR_Gtt_0l_A/razor_Va2_mass: {}
    #all/SR_Gtt_0l_A/razor_Vb2_mass: {}
    #all/SR_Gtt_0l_A/razor_GG_invGamma: {}
    #all/SR_Gtt_0l_A/razor_GG_mDeltaR: {}
    #all/SR_Gtt_0l_A/razor_Va1_n: {}
    #all/SR_Gtt_0l_A/razor_Vb1_n: {}
    #all/SR_Gtt_0l_A/razor_Ga_n: {}
    #all/SR_Gtt_0l_A/razor_Va2_n: {}
    #all/SR_Gtt_0l_A/razor_Vb2_n: {}
    #all/SR_Gtt_0l_A/razor_Gb_n: {}
    #all/SR_Gtt_0l_A/razor_GG_cosTheta: {}
    #all/SR_Gtt_0l_A/razor_Va1_cosTheta: {}
    #all/SR_Gtt_0l_A/razor_Vb1_cosTheta: {}
    #all/SR_Gtt_0l_A/razor_Va2_cosTheta: {}
    #all/SR_Gtt_0l_A/razor_Vb2_cosTheta: {}
    #all/SR_Gtt_0l_A/razor_GG_dPhiVis: {}
    #all/SR_Gtt_0l_A/razor_GG_dPhiBetaR: {}
    #all/SR_Gtt_0l_A/razor_GG_dPhiDecay: {}
    #all/SR_Gtt_0l_A/razor_dPhi_Ga_Ca1: {}
    #all/SR_Gtt_0l_A/razor_dPhi_Gb_Cb1: {}
    #all/SR_Gtt_0l_A/razor_pT_GG: {}
    #all/SR_Gtt_0l_A/razor_pZ_GG: {}
    #all/SR_Gtt_0l_A/razor_H11GG: {}
    #all/SR_Gtt_0l_A/razor_H21GG: {}
    #all/SR_Gtt_0l_A/razor_H22GG: {}
    #all/SR_Gtt_0l_A/razor_H41GG: {}
    #all/SR_Gtt_0l_A/razor_H42GG: {}
    #all/SR_Gtt_0l_A/razor_H11Ga: {}
    #all/SR_Gtt_0l_A/razor_H11Gb: {}
    #all/SR_Gtt_0l_A/razor_H21Ga: {}
    #all/SR_Gtt_0l_A/razor_H21Gb: {}
    #all/SR_Gtt_0l_A/razor_H11Ca1: {}
    #all/SR_Gtt_0l_A/razor_H11Cb1: {}
    #all/SR_Gtt_0l_A/razor_HT21GG: {}
    #all/SR_Gtt_0l_A/razor_HT22GG: {}
    #all/SR_Gtt_0l_A/razor_HT41GG: {}
    #all/SR_Gtt_0l_A/razor_HT42GG: {}
    #all/SR_Gtt_0l_A/razor_d_dPhiG: {}
    #all/SR_Gtt_0l_A/razor_s_dPhiG: {}
    #all/SR_Gtt_0l_A/razor_s_angle: {}
    #all/SR_Gtt_0l_A/razor_d_angle: {}
    #all/SR_Gtt_0l_A/razor_ratio_pZGG_HT21GG: {}
    #all/SR_Gtt_0l_A/razor_ratio_pZGG_HT41GG: {}
    #all/SR_Gtt_0l_A/razor_ratio_pTGG_HT21GG: {}
    #all/SR_Gtt_0l_A/razor_ratio_pTGG_HT41GG: {}
    #all/SR_Gtt_0l_A/razor_ratio_H11GG_H21GG: {}
    #all/SR_Gtt_0l_A/razor_ratio_HT41GG_H41GG: {}
    #all/SR_Gtt_0l_A/razor_ratio_H11GG_H41GG: {}
    #all/SR_Gtt_0l_B/met: {}
    #all/SR_Gtt_0l_B/meff: {}
    #all/SR_Gtt_0l_B/dphimetmin: {}
    #all/SR_Gtt_0l_B/mtb: {}
    #all/SR_Gtt_0l_B/njets: {}
    #all/SR_Gtt_0l_B/nbjets: {}
    #all/SR_Gtt_0l_B/ntops: {}
    #all/SR_Gtt_0l_B/razor_GG_mass: {}
    #all/SR_Gtt_0l_B/razor_Ga_mass: {}
    #all/SR_Gtt_0l_B/razor_Gb_mass: {}
    #all/SR_Gtt_0l_B/razor_Ca1_mass: {}
    #all/SR_Gtt_0l_B/razor_Cb1_mass: {}
    #all/SR_Gtt_0l_B/razor_Va1_mass: {}
    #all/SR_Gtt_0l_B/razor_Vb1_mass: {}
    #all/SR_Gtt_0l_B/razor_Va2_mass: {}
    #all/SR_Gtt_0l_B/razor_Vb2_mass: {}
    #all/SR_Gtt_0l_B/razor_GG_invGamma: {}
    #all/SR_Gtt_0l_B/razor_GG_mDeltaR: {}
    #all/SR_Gtt_0l_B/razor_Va1_n: {}
    #all/SR_Gtt_0l_B/razor_Vb1_n: {}
    #all/SR_Gtt_0l_B/razor_Ga_n: {}
    #all/SR_Gtt_0l_B/razor_Va2_n: {}
    #all/SR_Gtt_0l_B/razor_Vb2_n: {}
    #all/SR_Gtt_0l_B/razor_Gb_n: {}
    #all/SR_Gtt_0l_B/razor_GG_cosTheta: {}
    #all/SR_Gtt_0l_B/razor_Va1_cosTheta: {}
    #all/SR_Gtt_0l_B/razor_Vb1_cosTheta: {}
    #all/SR_Gtt_0l_B/razor_Va2_cosTheta: {}
    #all/SR_Gtt_0l_B/razor_Vb2_cosTheta: {}
    #all/SR_Gtt_0l_B/razor_GG_dPhiVis: {}
    #all/SR_Gtt_0l_B/razor_GG_dPhiBetaR: {}
    #all/SR_Gtt_0l_B/razor_GG_dPhiDecay: {}
    #all/SR_Gtt_0l_B/razor_dPhi_Ga_Ca1: {}
    #all/SR_Gtt_0l_B/razor_dPhi_Gb_Cb1: {}
    #all/SR_Gtt_0l_B/razor_pT_GG: {}
    #all/SR_Gtt_0l_B/razor_pZ_GG: {}
    #all/SR_Gtt_0l_B/razor_H11GG: {}
    #all/SR_Gtt_0l_B/razor_H21GG: {}
    #all/SR_Gtt_0l_B/razor_H22GG: {}
    #all/SR_Gtt_0l_B/razor_H41GG: {}
    #all/SR_Gtt_0l_B/razor_H42GG: {}
    #all/SR_Gtt_0l_B/razor_H11Ga: {}
    #all/SR_Gtt_0l_B/razor_H11Gb: {}
    #all/SR_Gtt_0l_B/razor_H21Ga: {}
    #all/SR_Gtt_0l_B/razor_H21Gb: {}
    #all/SR_Gtt_0l_B/razor_H11Ca1: {}
    #all/SR_Gtt_0l_B/razor_H11Cb1: {}
    #all/SR_Gtt_0l_B/razor_HT21GG: {}
    #all/SR_Gtt_0l_B/razor_HT22GG: {}
    #all/SR_Gtt_0l_B/razor_HT41GG: {}
    #all/SR_Gtt_0l_B/razor_HT42GG: {}
    #all/SR_Gtt_0l_B/razor_d_dPhiG: {}
    #all/SR_Gtt_0l_B/razor_s_dPhiG: {}
    #all/SR_Gtt_0l_B/razor_s_angle: {}
    #all/SR_Gtt_0l_B/razor_d_angle: {}
    #all/SR_Gtt_0l_B/razor_ratio_pZGG_HT21GG: {}
    #all/SR_Gtt_0l_B/razor_ratio_pZGG_HT41GG: {}
    #all/SR_Gtt_0l_B/razor_ratio_pTGG_HT21GG: {}
    #all/SR_Gtt_0l_B/razor_ratio_pTGG_HT41GG: {}
    #all/SR_Gtt_0l_B/razor_ratio_H11GG_H21GG: {}
    #all/SR_Gtt_0l_B/razor_ratio_HT41GG_H41GG: {}
    #all/SR_Gtt_0l_B/razor_ratio_H11GG_H41GG: {}
    #all/SR_Gtt_0l_C/met: {}
    #all/SR_Gtt_0l_C/meff: {}
    #all/SR_Gtt_0l_C/dphimetmin: {}
    #all/SR_Gtt_0l_C/mtb: {}
    #all/SR_Gtt_0l_C/njets: {}
    #all/SR_Gtt_0l_C/nbjets: {}
    #all/SR_Gtt_0l_C/ntops: {}
    #all/SR_Gtt_0l_C/razor_GG_mass: {}
    #all/SR_Gtt_0l_C/razor_Ga_mass: {}
    #all/SR_Gtt_0l_C/razor_Gb_mass: {}
    #all/SR_Gtt_0l_C/razor_Ca1_mass: {}
    #all/SR_Gtt_0l_C/razor_Cb1_mass: {}
    #all/SR_Gtt_0l_C/razor_Va1_mass: {}
    #all/SR_Gtt_0l_C/razor_Vb1_mass: {}
    #all/SR_Gtt_0l_C/razor_Va2_mass: {}
    #all/SR_Gtt_0l_C/razor_Vb2_mass: {}
    #all/SR_Gtt_0l_C/razor_GG_invGamma: {}
    #all/SR_Gtt_0l_C/razor_GG_mDeltaR: {}
    #all/SR_Gtt_0l_C/razor_Va1_n: {}
    #all/SR_Gtt_0l_C/razor_Vb1_n: {}
    #all/SR_Gtt_0l_C/razor_Ga_n: {}
    #all/SR_Gtt_0l_C/razor_Va2_n: {}
    #all/SR_Gtt_0l_C/razor_Vb2_n: {}
    #all/SR_Gtt_0l_C/razor_Gb_n: {}
    #all/SR_Gtt_0l_C/razor_GG_cosTheta: {}
    #all/SR_Gtt_0l_C/razor_Va1_cosTheta: {}
    #all/SR_Gtt_0l_C/razor_Vb1_cosTheta: {}
    #all/SR_Gtt_0l_C/razor_Va2_cosTheta: {}
    #all/SR_Gtt_0l_C/razor_Vb2_cosTheta: {}
    #all/SR_Gtt_0l_C/razor_GG_dPhiVis: {}
    #all/SR_Gtt_0l_C/razor_GG_dPhiBetaR: {}
    #all/SR_Gtt_0l_C/razor_GG_dPhiDecay: {}
    #all/SR_Gtt_0l_C/razor_dPhi_Ga_Ca1: {}
    #all/SR_Gtt_0l_C/razor_dPhi_Gb_Cb1: {}
    #all/SR_Gtt_0l_C/razor_pT_GG: {}
    #all/SR_Gtt_0l_C/razor_pZ_GG: {}
    #all/SR_Gtt_0l_C/razor_H11GG: {}
    #all/SR_Gtt_0l_C/razor_H21GG: {}
    #all/SR_Gtt_0l_C/razor_H22GG: {}
    #all/SR_Gtt_0l_C/razor_H41GG: {}
    #all/SR_Gtt_0l_C/razor_H42GG: {}
    #all/SR_Gtt_0l_C/razor_H11Ga: {}
    #all/SR_Gtt_0l_C/razor_H11Gb: {}
    #all/SR_Gtt_0l_C/razor_H21Ga: {}
    #all/SR_Gtt_0l_C/razor_H21Gb: {}
    #all/SR_Gtt_0l_C/razor_H11Ca1: {}
    #all/SR_Gtt_0l_C/razor_H11Cb1: {}
    #all/SR_Gtt_0l_C/razor_HT21GG: {}
    #all/SR_Gtt_0l_C/razor_HT22GG: {}
    #all/SR_Gtt_0l_C/razor_HT41GG: {}
    #all/SR_Gtt_0l_C/razor_HT42GG: {}
    #all/SR_Gtt_0l_C/razor_d_dPhiG: {}
    #all/SR_Gtt_0l_C/razor_s_dPhiG: {}
    #all/SR_Gtt_0l_C/razor_s_angle: {}
    #all/SR_Gtt_0l_C/razor_d_angle: {}
    #all/SR_Gtt_0l_C/razor_ratio_pZGG_HT21GG: {}
    #all/SR_Gtt_0l_C/razor_ratio_pZGG_HT41GG: {}
    #all/SR_Gtt_0l_C/razor_ratio_pTGG_HT21GG: {}
    #all/SR_Gtt_0l_C/razor_ratio_pTGG_HT41GG: {}
    #all/SR_Gtt_0l_C/razor_ratio_H11GG_H21GG: {}
    #all/SR_Gtt_0l_C/razor_ratio_HT41GG_H41GG: {}
    #all/SR_Gtt_0l_C/razor_ratio_H11GG_H41GG: {}
    all/Preselection/met: {ylabel : "events", xlabel : "met [GeV]"}
    all/Preselection/meff: {ylabel : "events", xlabel : "meff [GeV]", ymin: 0, ymax: 2000}
    all/Preselection/dphimetmin: {ylabel : "events", xlabel : "dphimetmin", ymin: 0, ymax: 4000}
    all/Preselection/mtb: {ylabel : "events", xlabel : "mtb [GeV]", ymin: 0, ymax: 4000}
    all/Preselection/njets: {ylabel : "events", xlabel : "njets", ymin: 0, ymax: 5000}
    all/Preselection/nbjets: {ylabel : "events", xlabel : "nbjets", ymin: 0, ymax: 7500}
    all/Preselection/ntops: {ylabel : "events", xlabel : "ntops", ymin: 0, ymax: 12500}
    all/Preselection/razor_GG_mass: {ylabel : "events", xlabel : "razor m^{GG} [GeV]", ymin: 0, ymax: 1000}
    all/Preselection/razor_Ga_mass: {ylabel : "events", xlabel : "razor m^{G_{a}}  [GeV]", ymin: 0, ymax: 2000, xmin: 0, xmax: 4000}
    all/Preselection/razor_Gb_mass: {ylabel : "events", xlabel : "razor m^{G_{b}}  [GeV]", ymin: 0, ymax: 2000, xmin: 0, xmax: 4000}
    all/Preselection/razor_Ca1_mass: {ylabel : "events", xlabel : "razor m^{C_{a1}} [GeV]", ymin: 0, ymax: 2500, xmin: 0, xmax: 2500}
    all/Preselection/razor_Cb1_mass: {ylabel : "events", xlabel : "razor m^{C_{b1}} [GeV]", ymin: 0, ymax: 2500, xmin: 0, xmax: 2500}
    all/Preselection/razor_Va1_mass: {ylabel : "events", xlabel : "razor m^{V_{a1}} [GeV]", ymin: 0, ymax: 2500, xmin: 0, xmax: 1000}
    all/Preselection/razor_Vb1_mass: {ylabel : "events", xlabel : "razor m^{V_{b1}} [GeV]", ymin: 0, ymax: 2500, xmin: 0, xmax: 1000}
    all/Preselection/razor_Va2_mass: {ylabel : "events", xlabel : "razor m^{V_{a2}} [GeV]", ymin: 0, ymax: 4000, xmin: 0, xmax: 750}
    all/Preselection/razor_Vb2_mass: {ylabel : "events", xlabel : "razor m^{V_{b2}} [GeV]", ymin: 0, ymax: 4000, xmin: 0, xmax: 750}
    all/Preselection/razor_GG_invGamma: {ylabel : "events", xlabel : "razor (#gamma^{GG})^{-1}", ymin: 0, ymax: 4000}
    all/Preselection/razor_GG_mDeltaR: {ylabel : "events", xlabel : "razor GG mDeltaR [GeV]", ymin: 0, ymax: 2000, xmin: 0, xmax: 4000}
    all/Preselection/razor_Va1_n: {ylabel : "events", xlabel : "razor n^{V_{a1}}", ymin: 0, ymax: 7500, xmin: 0, xmax: 10}
    all/Preselection/razor_Vb1_n: {ylabel : "events", xlabel : "razor n^{V_{b1}}", ymin: 0, ymax: 7500, xmin: 0, xmax: 10}
    all/Preselection/razor_Ga_n: {ylabel : "events", xlabel : "razor n^{G_{a}}", ymin: 0, ymax: 7500, xmin: 0, xmax: 10}
    all/Preselection/razor_Va2_n: {ylabel : "events", xlabel : "razor n^{V_{a2}}", ymin: 0, ymax: 7500, xmin: 0, xmax: 10}
    all/Preselection/razor_Vb2_n: {ylabel : "events", xlabel : "razor n^{V_{b2}}", ymin: 0, ymax: 7500, xmin: 0, xmax: 10}
    all/Preselection/razor_Gb_n: {ylabel : "events", xlabel : "razor n^{G_{b}}", ymin: 0, ymax: 7500, xmin: 0, xmax: 10}
    all/Preselection/razor_GG_cosTheta: {ylabel : "events", xlabel : "razor GG_cosTheta", ymin: 0, ymax: 3000}
    all/Preselection/razor_Va1_cosTheta: {ylabel : "events", xlabel : "razor Va1_cosTheta", ymin: 0, ymax: 2000}
    all/Preselection/razor_Vb1_cosTheta: {ylabel : "events", xlabel : "razor Vb1_cosTheta", ymin: 0, ymax: 2000}
    all/Preselection/razor_Va2_cosTheta: {ylabel : "events", xlabel : "razor Va2_cosTheta", ymin: 0, ymax: 2000}
    all/Preselection/razor_Vb2_cosTheta: {ylabel : "events", xlabel : "razor Vb2_cosTheta", ymin: 0, ymax: 2000}
    all/Preselection/razor_GG_dPhiVis: {ylabel : "events", xlabel : "razor GG_dPhiVis", ymin: 0, ymax: 5000}
    all/Preselection/razor_GG_dPhiBetaR: {ylabel : "events", xlabel : "razor GG_dPhiBetaR", ymin: 0, ymax: 2500}
    all/Preselection/razor_GG_dPhiDecay: {ylabel : "events", xlabel : "razor GG_dPhiDecay", ymin: 0, ymax: 2000}
    all/Preselection/razor_dPhi_Ga_Ca1: {ylabel : "events", xlabel : "razor dPhi_Ga_Ca1", ymin: 0, ymax: 2000}
    all/Preselection/razor_dPhi_Gb_Cb1: {ylabel : "events", xlabel : "razor dPhi_Gb_Cb1", ymin: 0, ymax: 2000}
    all/Preselection/razor_pT_GG: {ylabel : "events", xlabel : "razor p_{T}^{GG} [GeV]", ymin: 0, ymax: 3000, xmin: 0, xmax: 500}
    all/Preselection/razor_pZ_GG: {ylabel : "events", xlabel : "razor p_{Z}^{GG} [GeV]", ymin: 0, ymax: 1000, xmin: 0, xmax: 7500}
    all/Preselection/razor_H11GG: {ylabel : "events", xlabel : "razor H_{11}^{GG} [GeV]", ymin: 0, ymax: 3000, xmin: 0, xmax: 3500}
    all/Preselection/razor_H21GG: {ylabel : "events", xlabel : "razor H_{21}^{GG} [GeV]", ymin: 0, ymax: 1500, xmin: 0, xmax: 5000}
    all/Preselection/razor_H22GG: {ylabel : "events", xlabel : "razor H_{22}^{GG} [GeV]", ymin: 0, ymax: 1500, xmin: 0, xmax: 7500}
    all/Preselection/razor_H41GG: {ylabel : "events", xlabel : "razor H_{41}^{GG} [GeV]", ymin: 0, ymax: 1500, xmin: 0, xmax: 7500}
    all/Preselection/razor_H42GG: {ylabel : "events", xlabel : "razor H_{42}^{GG} [GeV]", ymin: 0, ymax: 1500, xmin: 0, xmax: 7500}
    all/Preselection/razor_H11Ga: {ylabel : "events", xlabel : "razor H_{11}^{Ga} [GeV]", ymin: 0, ymax: 3000, xmin: 0, xmax: 2000}
    all/Preselection/razor_H11Gb: {ylabel : "events", xlabel : "razor H_{11}^{Gb} [GeV]", ymin: 0, ymax: 3000, xmin: 0, xmax: 2000}
    all/Preselection/razor_H21Ga: {ylabel : "events", xlabel : "razor H_{21}^{Ga} [GeV]", ymin: 0, ymax: 3000, xmin: 0, xmax: 2500}
    all/Preselection/razor_H21Gb: {ylabel : "events", xlabel : "razor H_{21}^{Gb} [GeV]", ymin: 0, ymax: 3000, xmin: 0, xmax: 2500}
    all/Preselection/razor_H11Ca1: {ylabel : "events", xlabel : "razor H_{11}^{C_{a1}} [GeV]"}
    all/Preselection/razor_H11Cb1: {ylabel : "events", xlabel : "razor H_{11}^{C_{b1}} [GeV]"}
    all/Preselection/razor_HT21GG: {ylabel : "events", xlabel : "razor (H_{T})_{21}^{GG} [GeV]", ymin: 0, ymax: 1500, xmin: 0, xmax: 5000}
    all/Preselection/razor_HT22GG: {ylabel : "events", xlabel : "razor (H_{T})_{22}^{GG} [GeV]", ymin: 0, ymax: 1500, xmin: 0, xmax: 7500}
    all/Preselection/razor_HT41GG: {ylabel : "events", xlabel : "razor (H_{T})_{41}^{GG} [GeV]", ymin: 0, ymax: 1500, xmin: 0, xmax: 7500}
    all/Preselection/razor_HT42GG: {ylabel : "events", xlabel : "razor (H_{T})_{42}^{GG} [GeV]", ymin: 0, ymax: 1500, xmin: 0, xmax: 7500}
    all/Preselection/razor_d_dPhiG: {ylabel : "events", xlabel : "razor d_dPhiG", ymin: 0, ymax: 3000}
    all/Preselection/razor_s_dPhiG: {ylabel : "events", xlabel : "razor s_dPhiG", ymin: 0, ymax: 3000}
    all/Preselection/razor_s_angle: {ylabel : "events", xlabel : "razor s_angle", ymin: 0, ymax: 3000}
    all/Preselection/razor_d_angle: {ylabel : "events", xlabel : "razor d_angle", ymin: 0, ymax: 3000}
    all/Preselection/razor_ratio_pZGG_HT21GG: {ylabel : "events", xlabel : "razor p_{Z}^{GG}/(H_{T})_{21}^{GG}", ymin: 0, ymax: 2500, exclude: [W+jets, Z+jets, "1-top: t-channel", "1-top: Wt-inclusive", top EW, diboson, "t#bar{t}"]}
    all/Preselection/razor_ratio_pZGG_HT41GG: {ylabel : "events", xlabel : "razor p_{Z}^{GG}/(H_{T})_{41}^{GG}", ymin: 0, ymax: 2000, exclude: [W+jets, Z+jets, "1-top: t-channel", "1-top: Wt-inclusive", top EW, diboson, "t#bar{t}"]}
    all/Preselection/razor_ratio_pTGG_HT21GG: {ylabel : "events", xlabel : "razor p_{T}^{GG}/(H_{T})_{21}^{GG}", ymin: 0, ymax: 5000, exclude: [W+jets, Z+jets, "1-top: t-channel", "1-top: Wt-inclusive", top EW, diboson, "t#bar{t}"]}
    all/Preselection/razor_ratio_pTGG_HT41GG: {ylabel : "events", xlabel : "razor p_{T}^{GG}/(H_{T})_{41}^{GG}", ymin: 0, ymax: 10000, exclude: [W+jets, Z+jets, "1-top: t-channel", "1-top: Wt-inclusive", top EW, diboson, "t#bar{t}"]}
    all/Preselection/razor_ratio_H11GG_H21GG: {ylabel : "events", xlabel : "razor H_{11}^{GG}/H_{21}^{GG}", ymin: 0, ymax: 2500, exclude: [W+jets, Z+jets, "1-top: t-channel", "1-top: Wt-inclusive", top EW, diboson, "t#bar{t}"]}
    all/Preselection/razor_ratio_HT41GG_H41GG: {ylabel : "events", xlabel : "razor (H_{T})_{41}^{GG}/H_{41}^{GG}", ymin: 0, ymax: 2500, exclude: [W+jets, Z+jets, "1-top: t-channel", "1-top: Wt-inclusive", top EW, diboson, "t#bar{t}"]}
    all/Preselection/razor_ratio_H11GG_H41GG: {ylabel : "events", xlabel : "razor H_{11}^{GG}/H_{41}^{GG}", ymin: 0, ymax: 2500, exclude: [W+jets, Z+jets, "1-top: t-channel", "1-top: Wt-inclusive", top EW, diboson, "t#bar{t}"]}
